/**
 * upload-to-supabase.ts
 *
 * Reads knowledge.json (generated by combine-knowledge.ts)
 * and uploads all entries to the knowledge_entries table in Supabase
 * with embeddings generated via the Supabase embed edge function.
 *
 * Run: npx tsx src/scripts/upload-to-supabase.ts
 */

import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

interface KnowledgeItem {
  url: string;
  content: string;
}

async function getEmbedding(text: string): Promise<number[] | null> {
  try {
    const { data, error } = await supabase.functions.invoke("embed", {
      body: { input: text },
    });

    if (error) {
      console.error("Error invoking embed function:", error);
      return null;
    }

    return data.embedding;
  } catch (err) {
    console.error("Error fetching embedding:", err);
    return null;
  }
}

async function main() {
  const knowledgePath = path.resolve(process.cwd(), "src/lib/knowledge.json");
  const knowledgeData: KnowledgeItem[] = JSON.parse(
    fs.readFileSync(knowledgePath, "utf-8"),
  );

  console.log(`Found ${knowledgeData.length} items in knowledge.json`);

  let success = 0;
  let failed = 0;

  for (const item of knowledgeData) {
    const locale = item.url.includes("/pt/") || item.url.endsWith("/pt")
      ? "pt"
      : "en";

    // Parse title and metadata from content
    const titleMatch = item.content.match(/^# (.*)/m);
    const title = titleMatch ? titleMatch[1].trim() : "Untitled";

    const descriptionMatch = item.content.match(/^Description: (.*)/m);
    const description = descriptionMatch ? descriptionMatch[1].trim() : "";

    const tagsMatch = item.content.match(/^Tags: (.*)/m);
    const tags = tagsMatch ? tagsMatch[1].split(",").map((t) => t.trim()) : [];

    // Determine type from URL
    let type = "page";
    if (item.url.includes("/full-cv")) type = "cv";
    else if (item.url.includes("/projects/")) type = "project";
    else if (item.url.includes("/research/")) type = "research";
    else if (item.url.includes("/teaching/")) type = "teaching";
    else if (item.url.includes("/publications/")) type = "publication";

    console.log(`  [${type}] ${title.substring(0, 60)}...`);

    // Clean content for embedding
    const cleanContent = item.content.replace(/\r?\n|\r/g, " ").trim();
    const embedding = await getEmbedding(cleanContent);

    if (!embedding) {
      console.error(`  Failed to get embedding for: ${title}`);
      failed++;
      continue;
    }

    const entry = {
      content: item.content,
      url: item.url,
      title,
      type,
      metadata: { description, tags },
      locale,
      embedding,
    };

    const { error } = await supabase.from("knowledge_entries").insert([entry]);

    if (error) {
      console.error(`  Error inserting: ${error.message}`);
      failed++;
    } else {
      success++;
    }
  }

  console.log(`\nDone! Inserted: ${success}, Failed: ${failed}`);
}

main().catch(console.error);
