import {
  AlfredReinWorks,
  ArtEngineeringWorks,
  BuildSystemsWorks,
  Certifications,
  CoursesAttended,
  db,
  Education,
  EducationItems,
  Experience,
  ExperienceItems,
  FreelanceWorks,
  IcdItkeWorks,
  MarkoBrajovicWorks,
  Person,
  PersonToPublications,
  Publications,
  Scholarships,
  SkillDatabases,
  SkillDesign,
  SkillFrameworks,
  SkillProgramming,
  SkillSpecialized,
  Summary,
  TalksAndLectures,
  Tutoring,
} from "astro:db";

// https://astro.build/db/seed
export default async function seed() {
  await db.insert(Summary).values([
    {
      text: "Software developer with a robust interdisciplinary background spanning architectural design, computational technologies, and software engineering. Proven track record of bridging creative and technical domains, with expertise in web development, algorithmic design, and data visualization. Multilingual professional fluent in English, intermediate German and native Portuguese, passionate about leveraging interdisciplinary skills to solve complex problems through technology.",
      locale: "en",
    },
    {
      text: "Desenvolvedor de software com sólida formação interdisciplinar abrangendo design arquitetônico, tecnologias computacionais e engenharia de software. Histórico comprovado de unir domínios criativos e técnicos, com expertise em desenvolvimento web, design algorítmico e visualização de dados. Profissional multilíngue fluente em inglês, alemão intermediário e português nativo, apaixonado por resolver problemas complexos por meio da tecnologia.",
      locale: "pt",
    },
  ]);

  await db.insert(SkillProgramming).values([
    { id: 1, name: "HTML", level: "Advanced", locale: "en" },
    { id: 2, name: "CSS", level: "Advanced", locale: "en" },
    { id: 3, name: "JavaScript", level: "Advanced", locale: "en" },
    { id: 4, name: "Python", level: "Intermediate", locale: "en" },
    { id: 5, name: "C#", level: "Intermediate", locale: "en" },
  ]);

  await db.insert(SkillFrameworks).values([
    { id: 1, name: "Astro", level: "Advanced", locale: "en" },
    { id: 2, name: "React", level: "Advanced", locale: "en" },
    { id: 3, name: "Tailwind", level: "Advanced", locale: "en" },
    { id: 4, name: "Angular", level: "Intermediate", locale: "en" },
  ]);

  await db.insert(SkillDatabases).values([
    { id: 1, name: "SQLite", level: "Intermediate", locale: "en" },
    { id: 2, name: "PostgreSQL", level: "Intermediate", locale: "en" },
    { id: 3, name: "NoSQL", level: "Intermediate", locale: "en" },
  ]);

  await db.insert(SkillDesign).values([
    {
      id: 1,
      name: "Rhino",
      level: "Advanced",
      locale: "en",
    },
    {
      id: 2,
      name: "Grasshopper",
      level: "Advanced",
      locale: "en",
    },
    { id: 3, name: "Revit", level: "Advanced", locale: "en" },
    {
      id: 4,
      name: "Figma",
      level: "Intermediate",
      locale: "en",
    },
    { id: 5, name: "Adobe Creative Cloud", level: "Advanced", locale: "en" },
  ]);

  await db.insert(SkillSpecialized).values([
    { id: 1, name: "Web Development", locale: "en" },
    { id: 2, name: "Computational Design", locale: "en" },
    { id: 3, name: "UI/UX Design", locale: "en" },
  ]);

  await db.insert(Experience).values([
    {
      id: "BS",
      locale: "en",
      startDate: new Date("2024-01"),
      endDate: new Date("2024-12"),
      title: "Software Developer",
      company: "BuildSystems GmbH",
      companyNote: "Previously the startup Urban Scale Timber",
      location: "Munich, Germany",
      link: "https://buildsystems.de/",
    },
    {
      id: "UST",
      locale: "en",
      startDate: new Date("2023-1"),
      endDate: new Date("2023-12"),
      title: "Computational Architect",
      company: "Urban Scale Timber, Flügge Funding",
      companyNote: "The startup is now BuildSystems GmbH",
      location: "Munich, Germany",
      link: "https://urbanscaletimber.com/",
    },
    {
      id: "AE",
      locale: "en",
      startDate: new Date("2021-12"),
      endDate: new Date("2022-12"),
      title: "Computational Architect",
      company: "ArtEngineering GmbH",
      location: "Schorndorf, Germany",
      link: "https://art-engineering.net/",
    },
    {
      id: "AR",
      locale: "en",
      startDate: new Date("2020-10"),
      endDate: new Date("2021-11"),
      title: "Computational Architect",
      company: "Alfred Rein Ingenieure GmbH",
      location: "Stuttgart, Germany",
      link: "https://www.ar-ingenieure.com/",
    },
    {
      id: "ICD/ITKE",
      locale: "en",
      startDate: new Date("2019-12"),
      endDate: new Date("2020-10"),
      title: "Research Assistant",
      company: "ICD/ITKE University of Stuttgart",
      location: "Stuttgart, Germany",
      link: "https://www.icd.uni-stuttgart.de/",
    },
    {
      id: "AMB",
      locale: "en",
      startDate: new Date("2015-3"),
      endDate: new Date("2019-7"),
      title: "Computational Architect",
      titleNote: "Intern until December 2016",
      company: "Atelier Marko Brajovic",
      location: "São Paulo, Brazil",
      link: "https://markobrajovic.com/en",
    },
    {
      id: "CSULB",
      locale: "en",
      startDate: new Date("2014-6"),
      endDate: new Date("2014-8"),
      title: "On-the-job Training",
      company: "California State University Long Beach",
      location: "Long Beach, USA",
      link: "https://www.csulb.edu/college-of-engineering",
    },
    {
      id: "ICBUSP",
      locale: "en",
      startDate: new Date("2011-6"),
      endDate: new Date("2013-8"),
      title: "Graphic Designer",
      company: "Biomedical Science Institute - University of São Paulo",
      location: "Brazil",
      link: "https://ww3.icb.usp.br/",
    },
  ]);

  await db.insert(ExperienceItems).values([
    // BS
    {
      id: "BS1",
      experienceId: "BS",
      locale: "en",
      text: "Developed a Funding Calculator for new constructions and renovations in Germany. The web app was built with the Angular framework and PostgreSQL. It delivers a seamless UX and provide real-time financial modeling capabilities.",
    },
    {
      id: "BS2",
      experienceId: "BS",
      locale: "en",
      text: "Architected and implemented BuildSystems' website using Astro framework, leveraging Notion API to use Notion as a content management system (CMS).",
    },
    // UST
    {
      id: "UST1",
      experienceId: "UST",
      locale: "en",
      text: "Developed a specialized toolbox in C# for Grasshopper in conjunction with an object model (schema) and ontology.",
    },
    {
      id: "UST2",
      experienceId: "UST",
      locale: "en",
      text: "UI/UX prototype for the web app Circular Component Creator.",
    },
    {
      id: "UST3",
      experienceId: "UST",
      locale: "en",
      text: "Created data visualizations using Power BI for decision-making.",
    },
    {
      id: "UST4",
      experienceId: "UST",
      locale: "en",
      text: "Development of a timber component configurator with EPD data.",
    },
    {
      id: "UST5",
      experienceId: "UST",
      locale: "en",
      text: "Development of a tool for urban analysis.",
    },
    // AE
    {
      id: "AE1",
      experienceId: "AE",
      locale: "en",
      text: "Conducted algorithmic modeling and structural analysis of complex spatial structures and artworks.",
    },
    {
      id: "AE2",
      experienceId: "AE",
      locale: "en",
      text: "Developed design-to-production automated workflows.",
    },
    {
      id: "AE3",
      experienceId: "AE",
      locale: "en",
      text: "Aiding on structural analysis of complex spatial structures.",
    },
    {
      id: "AE4",
      experienceId: "AE",
      locale: "en",
      text: "Preparing meticulous technical documentation.",
    },
    {
      id: "AE5",
      experienceId: "AE",
      locale: "en",
      text: "Creating precise engineering drawings and production plans.",
    },
    // AR
    {
      id: "AR1",
      experienceId: "AR",
      locale: "en",
      text: "Received honorable mention in the competition 'Witterungsschutz Römermauer' from the city of Wiesbaden.",
    },
    {
      id: "AR2",
      experienceId: "AR",
      locale: "en",
      text: "Specialized in computational form finding of tensile structures.",
    },
    {
      id: "AR3",
      experienceId: "AR",
      locale: "en",
      text: "Simulated the deployment of a innovative inflatable membrane structure.",
    },
    {
      id: "AR4",
      experienceId: "AR",
      locale: "en",
      text: "Development of an automatized cutting pattern workflow for membranes.",
    },
    // ICD/ITKE
    {
      id: "ICD/ITKE1",
      experienceId: "ICD/ITKE",
      locale: "en",
      text: "Conducted natural fiber structural tests with Marta Gil Pérez.",
    },
    {
      id: "ICD/ITKE2",
      experienceId: "ICD/ITKE",
      locale: "en",
      text: "Carbon fiber winding research of Christoph Schlopschnat.",
    },
    {
      id: "ICD/ITKE3",
      experienceId: "ICD/ITKE",
      locale: "en",
      text: "Contributed to the computational design of a self-curving timber tower with Dylan Wood (similar to Urbach Tower).",
    },
    {
      id: "ICD/ITKE4",
      experienceId: "ICD/ITKE",
      locale: "en",
      text: "Assisted the ICD website migration with Tobias Schwinn.",
    },
    // AMB
    {
      id: "AMB1",
      experienceId: "AMB",
      locale: "en",
      text: "Executed CAD, BIM, and algorithmic modeling for diverse architectural projects.",
    },
    {
      id: "AMB2",
      experienceId: "AMB",
      locale: "en",
      text: "Managed project communications and supplier relationships.",
    },
    {
      id: "AMB3",
      experienceId: "AMB",
      locale: "en",
      text: "Developed conceptual designs and high-quality renderings.",
    },
    {
      id: "AMB4",
      experienceId: "AMB",
      locale: "en",
      text: "Led prototyping and digital fabrication initiatives.",
    },
    // CSULB
    {
      id: "CSULB1",
      experienceId: "CSULB",
      locale: "en",
      text: "Gained hands-on experience in project management.",
    },
    {
      id: "CSULB2",
      experienceId: "CSULB",
      locale: "en",
      text: "Conducted construction site inspections.",
    },
    {
      id: "CSULB3",
      experienceId: "CSULB",
      locale: "en",
      text: "Gained BIM modeling skills.",
    },
    {
      id: "CSULB4",
      experienceId: "CSULB",
      locale: "en",
      text: "Completed Safety and Health Training.",
    },
    // ICBUSP
    {
      id: "ICBUSP1",
      experienceId: "ICBUSP",
      locale: "en",
      text: "Created conceptual designs for scientific communications.",
    },
    {
      id: "ICBUSP2",
      experienceId: "ICBUSP",
      locale: "en",
      text: "Managed design project workflows.",
    },
    {
      id: "ICBUSP3",
      experienceId: "ICBUSP",
      locale: "en",
      text: "Organized and supported academic competition preparations.",
    },
  ]);

  await db.insert(Education).values([
    {
      id: "ITECH",
      locale: "en",
      startDate: new Date("2019-10"),
      endDate: new Date("2021-10"),
      title: "Master of Sciences",
      institution: "ITECH University of Stuttgart",
      location: "Stuttgart, Germany",
      link: "https://www.itech.uni-stuttgart.de/",
    },
    {
      id: "FAUUSP",
      locale: "en",
      startDate: new Date("2010-01"),
      endDate: new Date("2016-12"),
      title: "Bachelor of Architecture and Urbanism",
      institution: "FAUUSP",
      location: "São Paulo, Brazil",
      link: "https://www.fau.usp.br/",
    },
    {
      id: "AU/CADC",
      locale: "en",
      startDate: new Date("2014-01"),
      endDate: new Date("2014-12"),
      title: "Architecture Exchange Student",
      institution: "Auburn University – CADC",
      location: "Auburn, USA",
      link: "https://cadc.auburn.edu/",
    },
    {
      id: "AU/ESL",
      locale: "en",
      startDate: new Date("2013-08"),
      endDate: new Date("2013-12"),
      title: "Intensive English Program",
      institution: "Auburn Global",
      location: "Auburn, USA",
      link: "https://global.auburn.edu/english/",
    },
  ]);

  await db.insert(EducationItems).values([
    // ITECH
    {
      id: "ITECH1",
      educationId: "ITECH",
      locale: "en",
      text: "Thesis: Building Across Scales: A Robotic Timber Fabrication System for On-Site Press Gluing",
    },
    {
      id: "ITECH2",
      educationId: "ITECH",
      locale: "en",
      text: "Supervisors: Prof. Achim Menges, Prof. Jan Knippers",
    },

    // FAUUSP
    {
      id: "FAUUSP1",
      educationId: "FAUUSP",
      locale: "en",
      text: "Thesis: Architecture + Biomimetics + Algorithm",
    },
    {
      id: "FAUUSP2",
      educationId: "FAUUSP",
      locale: "en",
      text: "Supervisor: Prof. Arthur Lara",
    },
  ]);

  await db.insert(Scholarships).values([
    {
      id: "IntCDC",
      locale: "en",
      startDate: new Date("2021-03"),
      endDate: new Date("2021-10"),
      title: "IntCDC Master’s Thesis Grant 2021",
      institution: "Cluster of Excellence – IntCDC",
      description:
        "The Grant encourages excellent master’s students to realize a first step toward a prospective academic career.",
      link: "https://www.intcdc.uni-stuttgart.de/supporting-structures/early-career-and-education/grants-awards-overview/master-thesis-award-2021-1/",
    },
    {
      id: "CsF",
      locale: "en",
      startDate: new Date("2013-08"),
      endDate: new Date("2014-12"),
      title: "Science without Borders",
      institution: "Brazilian Federal Government",
      description:
        "Fully funded scholarships for the top Brazilian students. One year at Auburn University, USA.",
      link: "https://www.gov.br/cnpq/pt-br/acesso-a-informacao/acoes-e-programas/programas/ciencia-sem-fronteiras",
    },
  ]);

  await db.insert(Publications).values([
    {
      id: "ACJ2024",
      locale: "en",
      date: new Date("2024-09"),
      title:
        "Multi-scalar robotic fabrication system for on-site press gluing in multi-storey timber buildings",
      publisher: "Automation in Construction journal",
      link: "https://www.sciencedirect.com/science/article/pii/S0926580524005107",
    },
    {
      id: "CDRF2023",
      locale: "en",
      date: new Date("2023-06"),
      title:
        "Feedback-Based Design Method for Spatially-Informed and Structurally-Performative Column Placement in Multi-Story Construction",
      publisher: "CDRF 2023",
      location: "Beijing, China",
      link: "https://link.springer.com/chapter/10.1007/978-981-99-8405-3_5",
    },
    {
      id: "ECAADE2020",
      locale: "en",
      date: new Date("2020-06"),
      title: "Life Lamp: Connecting Design and People Through Emotion",
      publisher: "ECAADE 2020 Anthropologic",
      location: "Berlin, Germany",
      link: "/projects/life-lamp-by-estudio-guto-requena-for-decimal/",
    },
    {
      id: "CDS",
      locale: "en",
      date: new Date("2020-02"),
      title: "Computational Design Strategies",
      publisher: "Self-published",
      link: "/publications/computational-design-strategies/",
    },
    {
      id: "SiGradi2018",
      locale: "en",
      date: new Date("2018-11"),
      title: "High-Low as expression of the Brazilian digital fabrication",
      publisher: "SiGradi 2018 Technopolitics",
      location: "São Carlos, Brazil",
      link: "/publications/high-low-as-expression-of-the-brazilian-digital-fabrication/",
    },
    {
      id: "IASS2017",
      locale: "en",
      date: new Date("2017-09"),
      title: "Algorithmic design for traditional bobbin lace methods",
      publisher: "IASS 2017",
      location: "Hamburg, Germany",
      link: "/publications/algorithmic-design-for-traditional-bobbin-lace-methods/",
    },
  ]);

  await db
    .insert(Person)
    .values([
      { id: "Daniel Nunes Locatelli" },
      { id: "Nils Opgenorth" },
      { id: "Samuel Leder" },
      { id: "Achim Menges" },
      { id: "Ekin Sila Sahin" },
      { id: "Luis Orozco" },
      { id: "Anna Krtschil" },
      { id: "Hans Jakob Wagner" },
      { id: "Jan Knippers" },
      { id: "Leonardo Prazeres" },
      { id: "Guilherme Giantini" },
      { id: "Vitor Curti" },
      { id: "Carlos Augusto Requena" },
      { id: "Arthur Hunold Lara" },
      { id: "Ruy M O Pauletti" },
      { id: "Thiago H Omena" },
      { id: "Adalberto de Paula" },
    ]);

  await db.insert(PersonToPublications).values([
    // ACJ2024 (already added in previous code)
    { publicationId: "ACJ2024", personId: "Nils Opgenorth", order: 1 },
    { publicationId: "ACJ2024", personId: "Daniel Nunes Locatelli", order: 2 },
    { publicationId: "ACJ2024", personId: "Samuel Leder", order: 3 },
    { publicationId: "ACJ2024", personId: "Hans Jakob Wagner", order: 4 },
    { publicationId: "ACJ2024", personId: "Achim Menges", order: 5 },

    // CDRF2023
    { publicationId: "CDRF2023", personId: "Ekin Sila Sahin", order: 1 },
    { publicationId: "CDRF2023", personId: "Daniel Nunes Locatelli", order: 2 },
    { publicationId: "CDRF2023", personId: "Luis Orozco", order: 3 },
    { publicationId: "CDRF2023", personId: "Anna Krtschil", order: 4 },
    { publicationId: "CDRF2023", personId: "Hans Jakob Wagner", order: 5 },
    { publicationId: "CDRF2023", personId: "Achim Menges", order: 6 },
    { publicationId: "CDRF2023", personId: "Jan Knippers", order: 7 },

    // ECAADE2020
    {
      publicationId: "ECAADE2020",
      personId: "Daniel Nunes Locatelli",
      order: 1,
    },
    { publicationId: "ECAADE2020", personId: "Leonardo Prazeres", order: 2 },
    { publicationId: "ECAADE2020", personId: "Guilherme Giantini", order: 3 },
    { publicationId: "ECAADE2020", personId: "Vitor Curti", order: 4 },
    {
      publicationId: "ECAADE2020",
      personId: "Carlos Augusto Requena",
      order: 5,
    },

    // SiGradi2018
    {
      publicationId: "SiGradi2018",
      personId: "Daniel Nunes Locatelli",
      order: 1,
    },
    { publicationId: "SiGradi2018", personId: "Arthur Hunold Lara", order: 2 },
    {
      publicationId: "SiGradi2018",
      personId: "Ruy M O Pauletti",
      order: 3,
    },
    { publicationId: "SiGradi2018", personId: "Thiago H Omena", order: 4 },
    { publicationId: "SiGradi2018", personId: "Adalberto de Paula", order: 5 },

    // IASS2017
    { publicationId: "IASS2017", personId: "Daniel Nunes Locatelli", order: 1 },
    { publicationId: "IASS2017", personId: "Arthur Hunold Lara", order: 2 },
    {
      publicationId: "IASS2017",
      personId: "Ruy M O Pauletti",
      order: 3,
    },
    { publicationId: "IASS2017", personId: "Thiago H Omena", order: 4 },
  ]);

  await db.insert(Certifications).values([
    {
      id: "CS50SQL2024",
      locale: "en",
      date: new Date("2024-07"),
      title: "CS50's Introduction to Databases with SQL",
      issuer: "Harvard University & edX.org",
      location: "Online",
      link: "https://cs50.harvard.edu/certificates/581eaf67-0711-4c95-be9e-d4ec37eeeac1",
    },
    {
      id: "CS50CS2024",
      locale: "en",
      date: new Date("2024-07"),
      title: "CS50's Introduction to Computer Science",
      issuer: "Harvard University & edX.org",
      link: "https://cs50.harvard.edu/certificates/d05f22b7-5ebd-4433-9b12-ba626504cc2f",
    },
    {
      id: "MITX6001x2018",
      locale: "en",
      date: new Date("2018-08"),
      title: "Intro to Computer Science and Programming Using Python",
      issuer: "MITX & edX.org",
      credentialId: "6.00.1x",
      link: "https://courses.edx.org/certificates/f471f7bf0c46443cb32b66fd3988e0e3",
    },
    {
      id: "RevitArch2015-2016",
      locale: "en",
      date: new Date("2015-09"),
      title: "Revit Architecture Certified Professional Exam",
      issuer: "Autodesk University Brazil 2016",
      location: "São Paulo, Brazil",
      link: "https://www.credly.com/badges/0fbad904-5c7b-4739-b679-3b4d33be0f07",
    },
    {
      id: "CALOSHASafety2013",
      locale: "en",
      date: new Date("2013-07"),
      title: "Safety & Health Training",
      issuer: "CAL/OSHA",
      location: "Long Beach, USA",
      skills: "Construction Safety",
      credentialId: "10 Hours",
    },
  ]);

  await db.insert(Tutoring).values([
    {
      id: "ModelsByNature2019",
      locale: "en",
      startDate: new Date("2019-06"),
      endDate: new Date("2019-07"),
      title: "Models byNature 1.0 & 2.0",
      organization: "Self-organized",
      location: "São Paulo, Brazil",
      description:
        "This workshop connected natural design approaches like material computation and biomimetics with computational design.",
      link: "/teaching/models-bynature-10/",
    },
    {
      id: "TensegritySeminar2018",
      locale: "en",
      startDate: new Date("2018-12"),
      title: "Tensegrity Workshop",
      organization: "Atelier Marko Brajovic workshop",
      location: "Paraty, Brazil",
      description:
        "The team that formed the Atelier Marko Brajovic got together to develop a tensegrity collectively.",
      link: "https://markobrajovic.com/en/all/atelier-by-nature",
    },
    {
      id: "AdaptiveWorkshop2018",
      locale: "en",
      startDate: new Date("2018-06"),
      title: "Adaptive Grasshopper Workshop",
      organization: "XIV SAU UNEMAT",
      location: "Barra do Bugres, Brazil",
      description:
        'Workshop about the computational design strategy "Exoskeleton."',
      link: "/teaching/adaptive-grasshopper-workshop/",
    },
    {
      id: "KangarooWorkshop2017",
      locale: "en",
      startDate: new Date("2017-04"),
      title: "Grasshopper & Kangaroo Workshop",
      organization: "Porto FabLab",
      location: "São Paulo, Brazil",
      description: "Workshop about spring systems to simulate cloth behavior.",
    },
    {
      id: "RevitLessons2017",
      locale: "en",
      startDate: new Date("2017-02"),
      title: "Private Revit Lessons",
      organization: "Private Tutoring",
      location: "São Paulo, Brazil",
      description:
        "Revit lessons from the basic principles to advanced techniques.",
    },
  ]);

  await db.insert(TalksAndLectures).values([
    {
      id: "ForumHolzbau2024",
      locale: "en",
      date: new Date("2024-07"),
      title:
        "Multiskalares Roboterfertigungssystem für die Vor-Ort-Pressklebung im mehrgeschossigen Holzbau",
      organization: "Forum Holzbau",
      location: "Stuttgart, Germany",
      link: "https://www.icd.uni-stuttgart.de/news/Multiskalares-Roboterfertigungssystem-fuer-Vor-Ort-Pressklebung-im-mehrgeschossigen-Holzbau/",
    },
    {
      id: "GraphisoftX2023",
      locale: "en",
      date: new Date("2023-12"),
      title: "Vision Nachhaltigkeit",
      organization: "Graphisoft X",
      location: "Online",
      link: "https://www.youtube.com/watch?v=baVNIbWtMQo",
    },
    {
      id: "UFT2023",
      locale: "en",
      date: new Date("2023-11"),
      title: "Arquitetura Computacional",
      organization: "Architecture and Urbanism course at UFT",
      location: "Online",
      link: "https://sites.google.com/mail.uft.edu.br/semanau23/programa%C3%A7%C3%A3o/sexta-1011?authuser=0#h.rx3nv64mjv6q",
    },
    {
      id: "Siemens2023",
      locale: "en",
      date: new Date("2023-03"),
      title: "Feasibility of sustainable construction",
      organization: "Siemens RIE Munich Conference",
      location: "Munich, Germany",
      link: "https://ecosystem.siemens.com/researchandinnovation/rie-munich-conference-digitalization-low-code-engineering-in-industry",
    },
    {
      id: "IFPR2023",
      locale: "en",
      date: new Date("2023-09"),
      title: "Arquitetura Computacional na Alemanha: Estado da arte",
      organization: "Architecture and Urbanism course at IFPR",
      location: "Online",
    },
    {
      id: "DigitalFUTURES2022",
      locale: "en",
      date: new Date("2022-03"),
      title: "Building Across Scales (in portuguese)",
      organization: "DigitalFUTURES",
      location: "Online",
    },
    {
      id: "UNIP2020",
      locale: "en",
      date: new Date("2020-11"),
      title: "Computational Design: Strategies",
      organization: "UNIP Sorocaba",
      location: "Online",
    },
    {
      id: "PUCMinas2020",
      locale: "en",
      date: new Date("2020-10"),
      title: "Computational Design: Strategies",
      organization: "PUC Minas",
      location: "Online",
      link: "https://youtu.be/J303rzg7y0U",
    },
    {
      id: "IFRO2019",
      locale: "en",
      date: new Date("2019-07"),
      title: "Architecture + Biomimetics + Algorithm",
      organization: "Architecture and Urbanism Course at IFRO",
      location: "Vilhena, Brazil",
      link: "https://portal.ifro.edu.br/vilhena/noticias/8153-palestra-arquitetura-biomimetica-e-algoritmo-e-realizada-em-vilhena",
    },
    {
      id: "SEBRAE2019",
      locale: "en",
      date: new Date("2019-03"),
      title: "Emotional Design and Technology",
      organization: "SEBRAE Talks, MOVELPAR 2019",
      location: "Arapongas, Brazil",
    },
    {
      id: "SemanaDesignRio2018",
      locale: "en",
      date: new Date("2018-09"),
      title: "Parametric Design Inspired byNature",
      organization: "Semana Design Rio 2018",
      location: "Rio de Janeiro, Brazil",
      link: "https://revistacasaejardim.globo.com/Casa-e-Jardim/Eventos/Semana-Design-Rio/noticia/2018/09/semana-design-rio-chega-6-edicao-no-mam-entre-os-dias-13-e-1609.html",
    },
    {
      id: "Tatil2018",
      locale: "en",
      date: new Date("2018-08"),
      title: "Biomimetic Geometries",
      organization: "Tátil",
      location: "Rio de Janeiro, Brazil",
    },
    {
      id: "SAU2018",
      locale: "en",
      date: new Date("2018-06"),
      title: "Architecture + Biomimetics + Algorithm",
      organization: "XIV SAU UNEMAT",
      location: "Barra do Bugres, Brazil",
    },
    {
      id: "IED2017",
      locale: "en",
      date: new Date("2017-08"),
      title: "Architecture + Biomimetics + Algorithm",
      organization: "Istituto Europeo di Design (IED)",
      location: "São Paulo, Brazil",
    },
    {
      id: "FAU/POLI2016",
      locale: "en",
      date: new Date("2016-12"),
      title: "Form-finding with Grasshopper",
      organization: "II Structured Shell Meeting",
      location: "FAU/POLI USP, São Paulo, Brazil",
    },
  ]);

  await db.insert(CoursesAttended).values([
    {
      id: "CS50SQL2024",
      locale: "en",
      startDate: new Date("2024-06"),
      endDate: new Date("2024-07"),
      title: "CS50's Introduction to Databases with SQL",
      organization: "Harvard University",
      location: "Online",
      instructor: "Carter Zenke",
    },
    {
      id: "CS50CS2023",
      locale: "en",
      startDate: new Date("2023-07"),
      endDate: new Date("2023-10"),
      title: "CS50's Introduction to Computer Science",
      organization: "Harvard University",
      location: "Online",
      instructor: "David J. Malan",
    },
    {
      id: "DigitalFuturesIntelligence2020",
      locale: "en",
      startDate: new Date("2020-06"),
      endDate: new Date("2020-07"),
      title: "Intelligence",
      organization: "Digital Futures World 2020",
      location: "Online",
      instructor:
        "Neil Leach, Antoine Picon, Sanford Kwinter, and Marrikka Trotter",
    },
    {
      id: "WikiHouseSIGraDi2018",
      locale: "en",
      startDate: new Date("2018-11"),
      title: "Wiki-House: Generation and Digital-Material Construction",
      organization: "SIGraDi 2018",
      location: "São Carlos, Brazil",
      instructor: "Gonçalo Castro Henriques, and Andrés Passaro",
    },
    {
      id: "IASSOptimization2017",
      locale: "en",
      startDate: new Date("2017-09"),
      title:
        "Interfacing Architecture, Engineering, and Mathematical Optimization",
      organization: "IASS 2017",
      location: "Hamburg, Germany",
      instructor: "Thomas Wortmann and Judyta Cichocka",
    },
    {
      id: "FILEParametricDesign2017",
      locale: "en",
      startDate: new Date("2017-07"),
      title: "Parametric Design with Arduino and Grasshopper",
      organization: "FILE Festival",
      location: "São Paulo, Brazil",
      instructor: "Henrique Stabile",
    },
    {
      id: "RhinoDayGalapagos2016",
      locale: "en",
      startDate: new Date("2016-09"),
      title: "Workshop Grasshopper with Galapagos",
      organization: "Rhino Day",
      location: "FAU-Mackenzie, São Paulo, Brazil",
      instructor: "Victor Calixto",
    },
    {
      id: "FILEDigitalTheremin2016",
      locale: "en",
      startDate: new Date("2016-07"),
      title: "Digital Theremin with Arduino",
      organization: "FILE Festival",
      location: "São Paulo, Brazil",
      instructor: "Mauricio Jabur",
    },
    {
      id: "FILEDataDesign2016",
      locale: "en",
      startDate: new Date("2016-07"),
      title: "Data in the Design Process",
      organization: "FILE Festival",
      location: "São Paulo, Brazil",
      instructor: "Dyego Digiandomenico, Gabriele Landim, Henrique Fischer",
    },
    {
      id: "FabLabWoodwork2016",
      locale: "en",
      startDate: new Date("2016-06"),
      title: "Introduction to Woodwork",
      organization: "Fab Lab Livre SP",
      location: "São Paulo, Brazil",
      instructor: "Lucas S. M. Coutinho",
    },
    {
      id: "FabLabArduinoLEDS2016",
      locale: "en",
      startDate: new Date("2016-06"),
      title: "Arduino & LEDS",
      organization: "Fab Lab Livre SP",
      location: "São Paulo, Brazil",
      instructor: "Beatriz da Rocha",
    },
    {
      id: "RedBullElectronics2016",
      locale: "en",
      startDate: new Date("2016-06"),
      title: "Electronics in the darkness",
      organization: "Red Bull Station",
      location: "São Paulo, Brazil",
      instructor: "Lina Lopes",
    },
    {
      id: "FabLabElectronicsBasic2016",
      locale: "en",
      startDate: new Date("2016-06"),
      title: "Electronics Basic",
      organization: "Fab Lab Livre SP",
      location: "São Paulo, Brazil",
      instructor: "César A. G. de Alencar",
    },
    {
      id: "FabLabInteractivity2016",
      locale: "en",
      startDate: new Date("2016-05"),
      title: "Interactivity: Architecture and Responsive Design",
      organization: "Fab Lab Livre SP",
      location: "São Paulo, Brazil",
      instructor: "Ruairi Glynn and grad Students from UCL London",
    },
    {
      id: "FAUProcessing2011",
      locale: "en",
      startDate: new Date("2011-08"),
      endDate: new Date("2011-12"),
      title: "Fundamentals of Computation with Processing",
      organization: "FAU-USP",
      location: "São Paulo, Brazil",
      instructor: "Ricardo Nakamura",
    },
  ]);

  await db.insert(FreelanceWorks).values([
    {
      id: 1,
      locale: "en",
      title: "Life Lamp",
      startDate: new Date("2017-12"),
      category: "Computational Design",
      description:
        "Concept by Estudio Guto Requena for Decimal. Computational designer responsible for the program.",
    },
    {
      id: 2,
      locale: "en",
      title: "Margarita House",
      startDate: new Date("2017-06"),
      endDate: new Date("2017-08"),
      category: "Architectural Design",
      description: "Full middle class house renovation.",
      location: "São Paulo, Brazil",
    },
    {
      id: 3,
      locale: "en",
      title: "Burn",
      startDate: new Date("2016-06"),
      endDate: new Date("2016-11"),
      category: "Marketing Action",
      description: "Rendering of installations, bars and clothing.",
      location: "São Paulo, Brazil",
    },
    {
      id: 4,
      locale: "en",
      title: "Le Sandwich",
      startDate: new Date("2016-06"),
      category: "Architectural Design",
      description: "Converted a two-floors bank agency into a restaurant.",
      location: "São Paulo, Brazil",
    },
  ]);

  // BuildSystemsWorks table
  await db.insert(BuildSystemsWorks).values([
    {
      id: 1,
      locale: "en",
      title: "BuildSystems Website",
      startDate: new Date("2023-08"),
      endDate: new Date("2024-04"),
      category: "Web development",
      description:
        "Developed BuildSystems website in Astro, leveraging Notion API to use Notion as a CMS.",
    },
    {
      id: 2,
      locale: "en",
      title: "KfW Funding Calculator",
      startDate: new Date("2023-07"),
      endDate: new Date("2023-08"),
      category: "Web development",
      description:
        "Develoed the web app KfW Funding Calculator, using Angular and PostgreSQL.",
    },
    {
      id: 3,
      locale: "en",
      title: "Circular Component Creator",
      startDate: new Date("2023-06"),
      endDate: new Date("2023-07"),
      category: "UI/UX design",
      description:
        "Developed the interface for a web app to create building components.",
    },
    {
      id: 4,
      locale: "en",
      title: "BuildSystems Ontology",
      startDate: new Date("2023-03"),
      endDate: new Date("2023-06"),
      category: "Ontology design",
      description: "Research about schemas, object models and databases.",
    },
    {
      id: 5,
      locale: "en",
      title: "Grasshopper C# plugin",
      startDate: new Date("2023-03"),
      category: "Software development",
      description:
        "Developed a Grasshopper plugin with the functionality of previous configurators.",
    },
    {
      id: 6,
      locale: "en",
      title: "Data visualization with Power BI",
      startDate: new Date("2023-02"),
      category: "Data visualization",
      description:
        "Developed a workflow connecting Grasshopper data to Power BI.",
    },
    {
      id: 7,
      locale: "en",
      title: "Timber Component Configurator",
      startDate: new Date("2023-01"),
      endDate: new Date("2023-02"),
      category: "Computational design",
      description:
        "Development of a Grasshopper configurator for timber components using EPD data.",
    },
    {
      id: 8,
      locale: "en",
      title: "Urban Site Configurator",
      startDate: new Date("2023-01"),
      category: "Computational design",
      description:
        "Development of a Grasshopper configurator to create building envelopes.",
    },
    {
      id: 9,
      locale: "en",
      title: "Building Configurator",
      startDate: new Date("2023-01"),
      category: "Computational design",
      description: "Improvements on their early building configurator.",
    },
  ]);

  // ArtEngineeringWorks table
  await db.insert(ArtEngineeringWorks).values([
    {
      id: 1,
      locale: "en",
      title: "The curious desert",
      startDate: new Date("2021-10"),
      category: "Art installations",
      location: "Qatar desert",
      description:
        "Art installations by Olafur Eliasson. Detailing of steel structure.",
    },
    {
      id: 2,
      locale: "en",
      title: "AIDS",
      startDate: new Date("2022-09"),
      category: "Sculpture",
      location: "In front of Stedelijk Museum Amsterdam",
      description: "Technical and fabrication drawings.",
    },
    {
      id: 3,
      locale: "en",
      title: "Wood research",
      startDate: new Date("2022-08"),
      category: "Research",
      location: "Internal",
      description:
        "Researching cutting-edge technology in wood for the office.",
    },
    {
      id: 4,
      locale: "en",
      title: "Dome at Teshima Island",
      startDate: new Date("2022-08"),
      category: "Installation",
      location: "Teshima, Japan",
      description: "Technical drawings, logistics for transportation.",
    },
    {
      id: 5,
      locale: "en",
      title: "A harmonious cycle of interconnected nows",
      startDate: new Date("2022-07"),
      category: "Sculpture",
      location: "Azabudai Hills Gallery, Tokyo, Japan",
      description:
        "Sculpture by Olafur Eliasson. Aiding the detailing and prototyping; logistics for transportation.",
    },
    {
      id: 6,
      locale: "en",
      title: "Common Sky",
      startDate: new Date("2021-12"),
      endDate: new Date("2022-06"),
      category: "Complex spatial architecture",
      location: "Buffalo AKG Art Museum, Buffalo, USA",
      description:
        "By Studio Other Spaces. Parametric detailing and automated digital fabrication workflow.",
    },
    {
      id: 7,
      locale: "en",
      title: "ParaPivot",
      startDate: new Date("2022-05"),
      category: "Sculpture",
      location: "Archived",
      description:
        "Five-meters, steel and stone sculpture by Studio Alicja Kwade. Detailing of the structural framing.",
    },
    {
      id: 8,
      locale: "en",
      title: "Canyon",
      startDate: new Date("2022-01"),
      endDate: new Date("2022-02"),
      category: "Sculpture",
      location: "Louis Vuitton, Paris, France",
      description:
        "Seven-meters-tall steel sculpture by Katharina Grosse. Computational form-fitting using developable surfaces.",
    },
    {
      id: 9,
      locale: "en",
      title: "Donum",
      startDate: new Date("2022-01"),
      category: "Architectural Design",
      location: "Donum Estate, Sonoma, USA",
      description:
        "Vertical Panorama Pavilion by Studio Other Spaces. Wine-tasting space. Aiding the detailing.",
    },
  ]);

  await db.insert(AlfredReinWorks).values([
    {
      id: 1,
      locale: "en",
      title: "ZERO Tankstelle",
      startDate: new Date("2021-12"),
      category: "Steel and membrane structure",
      location: null,
      description: "Gas station typology. Rendering of the proposal.",
    },
    {
      id: 2,
      locale: "en",
      title: "Disney Wonder",
      startDate: new Date("2021-09"),
      endDate: new Date("2021-10"),
      category: "Retractable membrane cover",
      location: "Cruise",
      description: "Production of drawings for membrane fabrication.",
    },
    {
      id: 3,
      locale: "en",
      title: "Seilnetz Muttenz",
      startDate: new Date("2021-09"),
      endDate: new Date("2021-10"),
      category: "Cablenet structure",
      location: "Basel-Landschaft BBZ, Muttenz, Switzerland",
      description:
        "Form-finding of the cablenet structure and quantity takeoff.",
    },
    {
      id: 4,
      locale: "en",
      title: "Membranaustausch",
      startDate: new Date("2021-07"),
      category: "Water retention",
      location: "Schlosses Neuwildenstein, Österreich",
      description: "Mechanical drawings and rendering of the facade.",
    },
    {
      id: 5,
      locale: "en",
      title: "MVV Überdachung Vorplatz",
      startDate: new Date("2021-07"),
      category: "Membrane cover",
      location: "Mannheim, Germany",
      description: "Form-finding of membrane structures using Kangaroo 2.",
    },
    {
      id: 6,
      locale: "en",
      title: "Automatic cutting pattern",
      startDate: new Date("2021-02"),
      endDate: new Date("2021-06"),
      category: "Research",
      location: "Internal",
      description: "Development of automatized cutting patterns for membranes.",
    },
    {
      id: 7,
      locale: "en",
      title: "Radom Raisting",
      startDate: new Date("2021-03"),
      endDate: new Date("2021-05"),
      category: "Inflatable dome",
      location: "Raisting, Germany",
      description: "Simulation of the deployment and collision avoidance.",
    },
    {
      id: 8,
      locale: "en",
      title: "Neubau Parkhaus Swissprintersarea",
      startDate: new Date("2021-01"),
      category: "Facade detail",
      location: "Zofingen, Switzerland",
      description: "Mechanical drawings and rendering of the facade.",
    },
    {
      id: 9,
      locale: "en",
      title: "Witterungsschutz Römermauer",
      startDate: new Date("2021-01"),
      category: "Competition",
      location: "Wiesbaden, Germany",
      description:
        "Project coordination, membrane cover integrating the landscape.",
    },
    {
      id: 10,
      locale: "en",
      title: "Mechanical Bridge",
      startDate: new Date("2021-01"),
      category: "Bridge study",
      location: "Archived",
      description: "Simulation of the bridge opening and closing.",
    },
  ]);

  // IcdItkeWorks table
  await db.insert(IcdItkeWorks).values([
    {
      id: 1,
      locale: "en",
      title: "Coreless Filament Winding",
      startDate: new Date("2020-08"),
      endDate: new Date("2020-10"),
      category: "Structural Test",
      type: "Full-scale",
      location: "ICD CCL, Stuttgart, Germany",
      description: "Helped with the load tests of the livMatS pavilion.",
    },
    {
      id: 2,
      locale: "en",
      title: "ICD Website Migration",
      startDate: new Date("2019-12"),
      endDate: new Date("2020-10"),
      category: "Web development",
      type: "Online",
      location: null,
      description: "Migration of ICD's website to the new template in OpenCMS.",
    },
    {
      id: 3,
      locale: "en",
      title: "Carbon Filament Winding",
      startDate: new Date("2020-07"),
      category: "Photogrammetry",
      type: "Research",
      location: "ICD, Stuttgart, Germany",
      description:
        "Investigation of digital twins for small scale carbon fibre winding.",
    },
    {
      id: 4,
      locale: "en",
      title: "Tower using self-curving cross-laminated timber",
      startDate: new Date("2020-03"),
      endDate: new Date("2020-04"),
      category: "Computational Design",
      type: "Archived",
      location: null,
      description:
        "Computational designer for a project similar to the Urbach Tower.",
    },
  ]);

  // MarkoBraiovicWorks table
  await db.insert(MarkoBrajovicWorks).values([
    {
      id: 1,
      locale: "en",
      title: "BlastU 2019",
      startDate: new Date("2019-01"),
      endDate: new Date("2019-08"),
      category: "Parametric set and interior design",
      location: "Ibirapuera bienal pavilion, São Paulo, Brazil",
      description: "Architect in charge of design and supervision.",
    },
    {
      id: 2,
      locale: "en",
      title: "Casa e Jardim Award 2019",
      startDate: new Date("2019-06"),
      category: "Scenic design",
      location: "Pinacoteca de São Paulo, São Paulo, Brazil",
      description: "Architect in charge of the design and set-up follow-up.",
    },
    {
      id: 3,
      locale: "en",
      title: "Casa ITA",
      startDate: new Date("2019-04"),
      category: "House Design",
      location: "Paraty, Brazil",
      description: "Architect in charge of the design.",
    },
    {
      id: 4,
      locale: "en",
      title: "Itaú Rock in Rio 2019",
      startDate: new Date("2019-02"),
      endDate: new Date("2019-04"),
      category: "Parametric stage design",
      location: "Rio de Janeiro, Brazil",
      description:
        "Architect in charge of the design and code compliance (archived).",
    },
    {
      id: 5,
      locale: "en",
      title: "Embraer Pavilion",
      startDate: new Date("2019-01"),
      category: "Architectural Design",
      location: "Paris, France",
      description: "Architect in charge of the parametric façade.",
    },
    {
      id: 6,
      locale: "en",
      title: "Camper Thailand",
      startDate: new Date("2018-12"),
      category: "Parametric Interior Design",
      location: "Thailand",
      description: "Architect in charge of the design (archived).",
    },
    {
      id: 7,
      locale: "en",
      title: "The First Blow | Embraer",
      startDate: new Date("2018-11"),
      category: "Augmented Reality Sculpture",
      location: "T3 International Airport, São Paulo, Brazil",
      description: "Computational design support.",
    },
    {
      id: 8,
      locale: "en",
      title: "Animale Jewelry",
      startDate: new Date("2018-11"),
      endDate: new Date("2018-12"),
      category: "Parametric Façade",
      location: "Rio de Janeiro, Brazil",
      description: "Architect in charge of the design (archived).",
    },
    {
      id: 9,
      locale: "en",
      title: "Hitchcock – Suspense Backstage",
      startDate: new Date("2018-07"),
      endDate: new Date("2018-10"),
      category: "Exhibition",
      location: "MIS - Museu da Imagem e do Som, São Paulo, Brazil",
      description: "Artistic renderings.",
    },
    {
      id: 10,
      locale: "en",
      title: "Bar & Stage Heineken: Live Your Music",
      startDate: new Date("2018-06"),
      endDate: new Date("2018-11"),
      category: "Parametric design",
      location: "Meca Festival, Itinerant",
      description: "Parametric design, production, and supervision.",
    },
    {
      id: 11,
      locale: "en",
      title: "Nike Air Guitar",
      startDate: new Date("2018-03"),
      endDate: new Date("2018-04"),
      category: "Interactive Installation",
      location: "Red Bull Station, São Paulo, Brazil",
      description: "Design, arduino programming, production, and supervision.",
    },
    {
      id: 12,
      locale: "en",
      title: "Tidelli Wave",
      startDate: new Date("2017-08"),
      category: "Installation",
      location: "Tidelli showroom, São Paulo, Brazil",
      description: "Assembly supervision.",
    },
    {
      id: 13,
      locale: "en",
      title: "Homa Restaurant Refurbishment",
      startDate: new Date("2017-01"),
      endDate: new Date("2017-12"),
      category: "Interior Design",
      location: "São Paulo, Brazil",
      description: "Architect in charge of design and production",
    },
    {
      id: 14,
      locale: "en",
      title: "InsideOut",
      startDate: new Date("2017-06"),
      category: "Product Design",
      location: "Movecho",
      description: "Architect in charge of the design (archived).",
    },
    {
      id: 15,
      locale: "en",
      title: "House ASHA",
      startDate: new Date("2016-01"),
      endDate: new Date("2017-12"),
      category: "House Design",
      location: "Paraty, Brazil",
      description: "Architect in charge of detailing and supplier contact.",
    },
    {
      id: 16,
      locale: "en",
      title: "O3 Pavilion",
      startDate: new Date("2017-03"),
      category: "Parametric Pavilion",
      location: "Expo Revestir 2016, São Paulo, Brazil",
      description:
        "Responsible for the form-find of the final shape and extracting the documentation necessary for production.",
    },
    {
      id: 17,
      locale: "en",
      title: "Live Talks installation",
      startDate: new Date("2016-10"),
      category: "Installation",
      location: "Live talks 2016, São Paulo, Brazil",
      description:
        "Intern in charge of the design studies, production, and supervision.",
    },
    {
      id: 18,
      locale: "en",
      title: "Parada Coca-Cola",
      startDate: new Date("2016-08"),
      category: "Festival",
      location: "Pier Mauá, Rio de Janeiro, Brazil",
      description:
        "Intern in charge of the code to extract the documentation necessary for production.",
    },
    {
      id: 19,
      locale: "en",
      title: "Coca-Cola Taste of Fashion",
      startDate: new Date("2016-04"),
      category: "Set and interior design",
      location: "São Paulo Fashion Week, São Paulo, Brazil",
      description:
        "Designing, coding, and producing a tensegrity light sculpture.",
    },
    {
      id: 20,
      locale: "en",
      title: "Ekoa Park",
      startDate: new Date("2015-04"),
      endDate: new Date("2016-02"),
      category: "Ecological Park",
      location: "Morretes, Brazil",
      description: "Supervised intern in charge of detailing the project.",
    },
  ]);
}
